### PR TITLE
Add French Localization

### PR DESCRIPTION
**Pull request by ghivert**
Add French localization and rename English tests files to allow easy add of language in future.

### CODE REVIEW

**Comment by alpacaaa** [comment]
@ghivert Looks very good! The only thing I'm a little hesitant about merging is `frenchConfig` being exposed. I know 0.19 will probably improve how dead code gets eliminated, but I'm worried a lot of unnecessary stuff would get bundled in the final application – something I'd rather avoid. Also, the config is rather simple and I don't see much benefit in pre configuring it for the user.

Other than that I'm totally happy to merge, what do you think?

**Comment by ghivert** [comment]
You're right : I just forgot to expose the configuration... 😅

I think simplest configurations are good in general. Most of the time, you
don't want to bother if you have seconds or not. You want the text in your
language, and that's what frenchConfiguration aims to provide.
But I understand your point. If you think that such configurations are
useless, then I think it should be removed. Maybe let's see if more people
need it before adding it? I agree with the fact to not include not so
useful code if not needed.

**Comment by alpacaaa** [comment]
@ghivert sounds great then! If you could revert `src/Date/Distance.elm` to its original state I'd be happy to merge and release this!

Thanks 🙃

**Comment by ghivert** [comment]
Done! 🙂

**Comment by alpacaaa** [comment]
I'm seeing errors when running the tests, can you take a look?

```
-- TYPE MISMATCH ---------------- /Users/marco/dev/minghie/tests/FrenchTests.elm

The definition of `frenchLocale` does not match its type annotation.

24| frenchLocale : Bool -> Bool -> Config
25| frenchLocale prefix seconds =
26|>    { defaultConfig
27|>        | locale = French.locale { addPrefix = prefix }
28|>        , includeSeconds = seconds
29|>    }

The type annotation for `frenchLocale` says it always returns:

    Config

But the returned value (shown above) is a:

    { includeSeconds : Bool
    , locale : Date.Distance.Types.DistanceLocale -> String
    }

Hint: Problem in the `locale` field. It looks like a function needs 1 more
argument.

-- TYPE MISMATCH ---------------- /Users/marco/dev/minghie/tests/FrenchTests.elm

The argument to function `locale` is causing a mismatch.

27|                    French.locale { addPrefix = prefix }
                                     ^^^^^^^^^^^^^^^^^^^^^^
Function `locale` is expecting the argument to be:

    Order

But it is:

    { addPrefix : Bool }

Detected errors in 1 module.
```

**Comment by ghivert** [comment]
Corrected!

**Comment by alpacaaa** [comment]
Thanks @ghivert! I made some minor changes to the exposed functions and the tests so that they're more consisted. It's published in version `1.1.0` 🙂

**Pull request merged**
