### PR TITLE
Elm 0.19 upgrade attempt

### PR DESCRIPTION
**Pull request by AdrianoFerrari**
Hi @alpacaaa 

Turns out that your package is still the best for this, and I'd like to upgrade it to elm 0.19.
This is my initial attempt. Seems to work, but I don't know how to update the tests, so can't verify.

Could I get some feedback: What'd be the next step? Or can it be merged as is?

(Feel free to dive in and make any changes you feel are necessary)

### CODE REVIEW

**Comment by alpacaaa** [comment]
Hello @AdrianoFerrari , thanks for the PR!
Any reason why you removed the `Date.Extra` dependency? I would like the api to work with `Date` instead of primitives like `Int`. The helpers in `Date.Extra` make the operations more robust as well -- working with integers directly can be a bit dangerous.

**Comment by AdrianoFerrari** [comment]
Given that 0.19 seems to be recommending moving to Posix times instead of Dates (if I understand correctly). There doesn't seem to be an "officially sanctioned" `Date` representation, so it seemed much simpler to me to use `inWords : Posix -> Posix -> String`. That, and I couldn't find a `Date.Extra` package for 0.19 that had 1:1 correspondance with the old one.

All the internal logic seems to be `Int -> DistanceLocale` already anyway.

That said, I didn't look very hard. This PR is really just in the spirit of "better than nothing"...

Thoughts?

**Comment by alpacaaa** [comment]
Honestly haven't read anything about 0.19, didn't know Date was gone 😄. I will try to review in the coming days, thanks!

**Comment by AdrianoFerrari** [comment]
Or if you'd prefer to be done maintaining this project, I've been considering publishing my own package to do what this one does.

If so, we'll just close this PR and I'll clean up my version instead (very similar to yours, including multiple languages).

(Btw, closed by accident... hit the wrong button on phone )

**Comment by AdrianoFerrari** [comment]
FYI I published my package here:
https://package.elm-lang.org/packages/gingko/time-distance/latest/

Tried to keep the language functions simple (i.e. plain strings wherever possible, instead of `circa` and other functions).

**Comment by alpacaaa** [comment]
Looks great 👍

**Pull request closed without merging**
